### ISSUE TITLE
aegir should be a devDependency

### ISSUE THREAD

**Issue by MichaelMure** [ipld/js-ipld-eth-storage-trie#3]
More details here: https://github.com/dignifiedquire/aegir/issues/128#issuecomment-298324150

Currently, using this package will pull react and friends.

**Comment by kenshyx** [comment]
This also  breaks electron-rebuild for native packages.

**Comment by dignifiedquire** [comment]
also please update to the latest https://github.com/ipfs/aegir/issues/133 as this is causing issues
